name: Build Jarvis APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  MODULE: app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests (optional)
        run: ./gradlew test

      - name: Build debug APK
        run: ./gradlew "${{ env.MODULE }}:assembleDebug"

      - name: Build release APK
        run: ./gradlew "${{ env.MODULE }}:assembleRelease"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: jarvis-debug-apk
          path: ${{ env.MODULE }}/build/outputs/apk/debug/*.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: jarvis-release-apk
          path: ${{ env.MODULE }}/build/outputs/apk/release/*.apk
